### PR TITLE
Add VAST 4.2 and SIMID 1.0 to lists

### PR DESCRIPTION
**Pull request by aronschatz**

### CODE REVIEW

**Comment by aronschatz** [comment]
Bump. Both standards are going to be released at the end of June.

**Review by git4skatz — APPROVED** [review]

**Comment by aronschatz** [comment]
Can we merge this request? The two standards have been released.

**Comment by goosemanjack** [comment]
This is not yet final. One spec issue came up regarding the location of the ClickThrough element under Wrapper which needs to be clarified. I would like this resolved before we merge and release the 4.2 xsd.

**Comment by aronschatz** [comment]
@goosemanjack This is not a VAST repo, it is to add these to AdCOM lists. Totally distinct from each other.

**Comment by goosemanjack** [comment]
My bad. I have a different PR on the vast repo and conflated the two. Thanks for pointing this out to me.

**Comment by aronschatz** [comment]
No problem, just making sure.

**Comment by iantri** [comment]
I have resolved this as a part of a general update to the spec doc. Thus, while I am closing the pull request without merging, you should now find that VAST 4.2 and SIMID 1.0 are present.

**Pull request closed without merging**
