### PR TITLE
Add SafeFrame 2.0 to API Framework

### PR DESCRIPTION
**Pull request by aronschatz**
Also correct minor HTML error in SIMID 1.1 table (extra </tr> removed)

### CODE REVIEW

**Comment by aronschatz** [comment]
This is from the SafeFrame working group to enable CATS/OpenRTB request to signal SafeFrame 2.0 support at bid/request time.

**Comment by iantri** [comment]
Mostly a memo-to-self for things we should probably talk about:
- We never indicated SafeFrame 1.0 in bid requests.
- I realize SafeFrame is not just about expansion, but we should probably talk about and document expected bidder logic for determining when an expandable ad is technically capable of being served.  This was already unclear, and addition of SafeFrame 2.0 in APIs list muddies it further, however we can fix that through clear documentation..

**Comment by amitshetty** [comment]
Is this something we should look at merging? @iantri @aronschatz

**Comment by aronschatz** [comment]
Not anymore. SafeFrame 2.0 is no longer a thing. SHARC will be, though. I'll have a PR for that when needed. This can be closed.

**Pull request closed without merging**
