### PR TITLE
Propose new field 'kwarray' to replace 'keywords', in each of 3 places

### PR DESCRIPTION
**Pull request by simontrasler**

### CODE REVIEW

**Comment by amitshetty** [comment]
Is this something we should look at in the working group? @iantri @simontrasler

**Comment by simontrasler** [comment]
@amitshetty thanks, yes please add to the list for 2.6. Hopefully easy to resolve.

**Comment by amitshetty** [comment]
@simontrasler - what is the driver for this change? Seems like the value of making this change is minimal...

**Comment by simontrasler** [comment]
This came up in one of the Working Group meetings and I volunteered to make the pull request. I ask @iantri please add your own color, though for my 2 cents it's about getting us to a place of better modeling -- the value *is* an array, and a comma-delimited string causes problems when the individual elements also contain commas.

**Comment by amitshetty** [comment]
Note from Commit Group call - Rather than make this breaking change, we might want to just clarify how commas etc should be encoded/handled.

**Pull request merged**
